name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1
      - run: zig version
      - run: zig build
      - run: zig test src/main.zig
